2023-09-15 17:32:36,676 INFO: Video processing has begun [in /Users/p/Documents/Github/surveil/video_app/utils.py:227]
2023-09-15 17:32:44,802 INFO: Video processing has finished [in /Users/p/Documents/Github/surveil/video_app/utils.py:235]
2023-09-15 17:32:44,802 INFO: Class Detections method write_images() has begun [in /Users/p/Documents/Github/surveil/video_app/utils.py:243]
2023-09-15 17:32:45,408 INFO: images successfully written locally [in /Users/p/Documents/Github/surveil/video_app/utils.py:247]
2023-09-15 17:32:45,408 INFO: csv successfully written locally [in /Users/p/Documents/Github/surveil/video_app/utils.py:257]
2023-09-15 17:32:45,744 INFO: images successfully written to s3 bucket [in /Users/p/Documents/Github/surveil/video_app/utils.py:267]
2023-09-15 17:32:47,921 INFO: csv successfully written to s3 bucket [in /Users/p/Documents/Github/surveil/video_app/utils.py:274]
2023-09-15 17:32:48,223 INFO: Deleted file /Users/p/Documents/Github/surveil/temp_data/images/detection5_person.jpg [in /Users/p/Documents/Github/surveil/video_app/routes/main_routes.py:180]
2023-09-15 17:32:48,223 INFO: Deleted file /Users/p/Documents/Github/surveil/temp_data/images/detection2_car.jpg [in /Users/p/Documents/Github/surveil/video_app/routes/main_routes.py:180]
2023-09-15 17:32:48,223 INFO: Deleted file /Users/p/Documents/Github/surveil/temp_data/images/detection6_person.jpg [in /Users/p/Documents/Github/surveil/video_app/routes/main_routes.py:180]
2023-09-15 17:32:48,223 INFO: Deleted file /Users/p/Documents/Github/surveil/temp_data/images/detection1_person.jpg [in /Users/p/Documents/Github/surveil/video_app/routes/main_routes.py:180]
2023-09-15 17:32:48,223 INFO: Deleted file /Users/p/Documents/Github/surveil/temp_data/images/detection3_train.jpg [in /Users/p/Documents/Github/surveil/video_app/routes/main_routes.py:180]
2023-09-15 17:32:48,223 INFO: Deleted file /Users/p/Documents/Github/surveil/temp_data/images/detection4_person.jpg [in /Users/p/Documents/Github/surveil/video_app/routes/main_routes.py:180]
2023-09-15 17:32:48,223 INFO: Deleted file /Users/p/Documents/Github/surveil/temp_data/csvs/data_20230915_173245.csv [in /Users/p/Documents/Github/surveil/video_app/routes/main_routes.py:180]
2023-09-15 17:32:48,223 INFO: Deleted file /Users/p/Documents/Github/surveil/temp_data/videos/VIRAT_000001-0210-0220.mp4 [in /Users/p/Documents/Github/surveil/video_app/routes/main_routes.py:180]
2023-09-15 18:14:57,770 INFO: Video App startup [in /Users/p/Documents/Github/surveil/video_app/__init__.py:40]
2023-09-15 18:15:03,257 INFO: Processing route was hit! [in /Users/p/Documents/Github/surveil/video_app/routes/main_routes.py:114]
2023-09-15 18:15:03,277 INFO: Video processing has begun [in /Users/p/Documents/Github/surveil/video_app/utils.py:246]
2023-09-15 18:15:54,777 ERROR: Exception on /processing [GET] [in /Users/p/miniconda3/envs/video-metrics/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/p/miniconda3/envs/video-metrics/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/p/miniconda3/envs/video-metrics/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/p/miniconda3/envs/video-metrics/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/p/miniconda3/envs/video-metrics/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/p/Documents/Github/surveil/video_app/routes/main_routes.py", line 130, in processing
    detectionsInVideo.process_video(model, VIDEO, CLASSES)
  File "/Users/p/Documents/Github/surveil/video_app/utils.py", line 249, in process_video
    self.df = get_df(self.results, VIDEO)
  File "/Users/p/Documents/Github/surveil/video_app/utils.py", line 65, in get_df
    fps = get_frame_rate(VIDEO)
  File "/Users/p/Documents/Github/surveil/video_app/utils.py", line 42, in get_frame_rate
    cap = cv2.VideoCapture(video_path)
NameError: name 'video_path' is not defined
2023-09-18 12:34:18,862 INFO: Video App startup [in /Users/p/Documents/Github/surveil/video_app/__init__.py:40]
2023-09-18 12:36:35,999 INFO: Processing route was hit! [in /Users/p/Documents/Github/surveil/video_app/routes/main_routes.py:116]
2023-09-18 12:36:36,015 INFO: Video processing has begun [in /Users/p/Documents/Github/surveil/video_app/utils.py:246]
2023-09-18 12:42:00,640 ERROR: Exception on /processing [GET] [in /Users/p/miniconda3/envs/video-metrics/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/p/miniconda3/envs/video-metrics/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/p/miniconda3/envs/video-metrics/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/p/miniconda3/envs/video-metrics/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/p/miniconda3/envs/video-metrics/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/p/Documents/Github/surveil/video_app/routes/main_routes.py", line 133, in processing
    detectionsInVideo.process_video(model, VIDEO, CLASSES)
  File "/Users/p/Documents/Github/surveil/video_app/utils.py", line 249, in process_video
    self.df = get_df(self.results, VIDEO)
  File "/Users/p/Documents/Github/surveil/video_app/utils.py", line 83, in get_df
    timestamps.append(frame / fps)  # timestamp
ZeroDivisionError: float division by zero
2023-09-18 19:13:04,615 INFO: Video App startup [in /Users/p/Documents/Github/surveil/video_app/__init__.py:40]
2023-09-19 11:30:15,811 INFO: Video App startup [in /Users/p/Documents/Github/surveil/video_app/__init__.py:40]
2023-09-19 11:30:38,845 INFO: Processing route was hit! [in /Users/p/Documents/Github/surveil/video_app/routes/main_routes.py:120]
2023-09-19 11:30:38,871 ERROR: Exception on /processing [GET] [in /Users/p/miniconda3/envs/video-metrics/lib/python3.10/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/p/miniconda3/envs/video-metrics/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/p/miniconda3/envs/video-metrics/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/p/miniconda3/envs/video-metrics/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/p/miniconda3/envs/video-metrics/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/p/Documents/Github/surveil/video_app/routes/main_routes.py", line 139, in processing
    detectionsInVideo.process_video(model, VIDEO, CLASSES)
TypeError: Detections.process_video() missing 1 required positional argument: 'YOUTUBE'
2023-09-19 11:31:48,929 INFO: Video App startup [in /Users/p/Documents/Github/surveil/video_app/__init__.py:40]
2023-09-19 11:31:59,365 INFO: Processing route was hit! [in /Users/p/Documents/Github/surveil/video_app/routes/main_routes.py:120]
2023-09-19 11:31:59,382 INFO: Video processing has begun [in /Users/p/Documents/Github/surveil/video_app/utils.py:338]
2023-09-19 11:32:07,714 INFO: Video processing has finished [in /Users/p/Documents/Github/surveil/video_app/utils.py:347]
2023-09-19 11:32:07,714 INFO: csv successfully written locally [in /Users/p/Documents/Github/surveil/video_app/utils.py:369]
2023-09-19 11:32:08,134 INFO: Class Detections method write_images() has begun [in /Users/p/Documents/Github/surveil/video_app/utils.py:355]
2023-09-19 11:32:08,764 INFO: images successfully written locally [in /Users/p/Documents/Github/surveil/video_app/utils.py:359]
2023-09-19 11:32:10,786 INFO: images successfully written to s3 bucket [in /Users/p/Documents/Github/surveil/video_app/routes/main_routes.py:168]
